<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="rbiradar-t460" name="com.tibco.rest.test.DataDrivenTestCases" tests="16" failures="1" timestamp="23 Aug 2021 12:24:58 GMT" time="13.201" errors="15">
  <testcase name="testcase" time="0.685" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.739" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.743" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.717" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.754" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.716" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.695" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.814" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.719" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.732" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.751" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.033" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.926" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.799" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should contains &quot;Auto Role Edited  you have entered  is already in use&quot; : Actual value is &quot;Auto Role Edited  you have entered  is already in use&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should contains "Auto Role Edited  you have entered  is already in use" : Actual value is "Auto Role Edited  you have entered  is already in use"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertContains(Assertions.java:212)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:533)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.720" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.658" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
</testsuite> <!-- com.tibco.rest.test.DataDrivenTestCases -->
