<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="kereddy-t460" name="com.tibco.rest.test.DataDrivenTestCases" tests="506" failures="44" timestamp="16 Nov 2021 05:40:50 GMT" time="372.723" errors="462">
  <testcase name="testcase" time="0.657" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.624" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.729" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should contains &quot;Name  you have entered  is already in use&quot; : Actual value is &quot;Name  you have entered  is already in use&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should contains "Name  you have entered  is already in use" : Actual value is "Name  you have entered  is already in use"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertContains(Assertions.java:212)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:533)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:377)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.794" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.651" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.647" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.685" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.726" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.691" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.664" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.791" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.735" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should be &quot;EZComm&quot; : Actual value is &quot;EDIFACT&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should be "EZComm" : Actual value is "EDIFACT"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertEquals(Assertions.java:183)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:508)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.652" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should not be &quot;[]&quot; : Actual value is &quot;[]&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should not be "[]" : Actual value is "[]"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertNotEquals(Assertions.java:196)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:520)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:344)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.803" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.005" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error type="java.net.URISyntaxException" message="Illegal character in path at index 55: http://10.102.16.61:30001/cms/v1/operations/RosettaNet/[]">
      <![CDATA[java.net.URISyntaxException: Illegal character in path at index 55: http://10.102.16.61:30001/cms/v1/operations/RosettaNet/[]
	at java.net.URI$Parser.fail(Unknown Source)
	at java.net.URI$Parser.checkChars(Unknown Source)
	at java.net.URI$Parser.parseHierarchical(Unknown Source)
	at java.net.URI$Parser.parse(Unknown Source)
	at java.net.URI.<init>(Unknown Source)
	at io.restassured.internal.http.URIBuilder.convertToURI(URIBuilder.java:91)
	at io.restassured.internal.http.URIBuilder$convertToURI.call(Unknown Source)
	at io.restassured.internal.RequestSpecificationImpl.generateRequestUriForLogging(RequestSpecificationImpl.groovy:1193)
	at sun.reflect.GeneratedMethodAccessor33.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:815)
	at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:174)
	at io.restassured.internal.RequestSpecificationImpl.newFilterContext(RequestSpecificationImpl.groovy:1154)
	at sun.reflect.GeneratedMethodAccessor32.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:815)
	at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
	at io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1729)
	at sun.reflect.GeneratedMethodAccessor65.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:815)
	at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
	at io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1737)
	at sun.reflect.GeneratedMethodAccessor64.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:815)
	at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
	at io.restassured.internal.RequestSpecificationImpl.get(RequestSpecificationImpl.groovy:170)
	at io.restassured.internal.RequestSpecificationImpl.get(RequestSpecificationImpl.groovy)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:210)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </error>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.763" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.618" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.796" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.660" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.786" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.614" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.764" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.802" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.696" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.990" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.887" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.660" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Unable to store response string to variable or couldn&#039;t received response.">
      <![CDATA[java.lang.AssertionError: Unable to store response string to variable or couldn't received response.
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:415)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.633" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.833" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.717" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.799" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.906" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.620" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Response Code is 500">
      <![CDATA[java.lang.AssertionError: Response Code is 500
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:460)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.787" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.635" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.608" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.624" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.776" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.740" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.790" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.629" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.684" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.835" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.684" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.631" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.641" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should be &quot;RosettaNet&quot; : Actual value is &quot;EZComm&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should be "RosettaNet" : Actual value is "EZComm"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertEquals(Assertions.java:183)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:508)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.765" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.682" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.668" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.636" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.629" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.907" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.638" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.665" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.630" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.756" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.698" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.620" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.653" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should contains &quot;The password you have entered does not match&quot; : Actual value is &quot;The password you have entered does not match&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should contains "The password you have entered does not match" : Actual value is "The password you have entered does not match"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertContains(Assertions.java:212)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:533)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.704" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.906" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.654" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.634" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.625" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.632" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.640" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.649" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.612" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.666" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.678" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.642" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.638" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.618" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.668" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.096" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.674" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.693" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should not be &quot;&quot; : Actual value is &quot;&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should not be "" : Actual value is ""
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertNotEquals(Assertions.java:196)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:520)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:377)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.700" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.226" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should contains &quot;sccode1 you have entered  is already in use&quot; : Actual value is &quot;sccode1 you have entered  is already in use&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should contains "sccode1 you have entered  is already in use" : Actual value is "sccode1 you have entered  is already in use"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertContains(Assertions.java:212)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:533)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:377)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.704" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.712" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.650" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.630" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.869" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.759" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.642" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.650" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.853" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.848" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.718" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.649" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.889" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.932" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.637" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.624" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Response Code is 500">
      <![CDATA[java.lang.AssertionError: Response Code is 500
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:460)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.671" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.734" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.673" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.615" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.629" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.683" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.623" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.899" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.696" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.776" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.661" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.629" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should be &quot;CMName1&quot; : Actual value is &quot;&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should be "CMName1" : Actual value is ""
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertEquals(Assertions.java:183)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:508)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:377)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.625" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.962" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.638" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.940" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.661" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.668" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.650" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.707" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.719" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.812" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.634" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.682" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.633" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.755" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.780" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.648" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.622" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.779" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.644" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.732" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.639" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.642" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.652" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.823" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.653" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.604" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.896" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.646" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.657" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.612" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.905" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.810" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.662" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.623" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.645" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.664" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.620" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.642" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.854" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.680" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.760" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.775" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.659" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.669" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.640" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should contains &quot;Invalid credentials&quot; : Actual value is &quot;Invalid credentials&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should contains "Invalid credentials" : Actual value is "Invalid credentials"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertContains(Assertions.java:212)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:533)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.651" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="7.448" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.624" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.654" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.644" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.652" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.638" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should be &quot;CMName1&quot; : Actual value is &quot;&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should be "CMName1" : Actual value is ""
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertEquals(Assertions.java:183)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:508)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:377)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.661" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.633" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.748" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.884" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.650" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.820" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.876" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.727" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.676" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.624" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.642" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.641" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.945" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.717" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.693" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should contains &quot;RN Role Test you have entered  is already in use&quot; : Actual value is &quot;RN Role Test you have entered  is already in use&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should contains "RN Role Test you have entered  is already in use" : Actual value is "RN Role Test you have entered  is already in use"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertContains(Assertions.java:212)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:533)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.663" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.414" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.640" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should be &quot;CMName&quot; : Actual value is &quot;&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should be "CMName" : Actual value is ""
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertEquals(Assertions.java:183)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:508)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:377)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.853" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.741" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.807" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.680" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.612" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.640" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should contains &quot;false&quot; : Actual value is &quot;false&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should contains "false" : Actual value is "false"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertContains(Assertions.java:212)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:533)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:377)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.800" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.684" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.876" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.705" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.681" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.696" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.758" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.631" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.613" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.553" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.959" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.932" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.807" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.646" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.833" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.632" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.123" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.713" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.860" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.631" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.877" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.686" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.956" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.734" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.628" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.821" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.771" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.780" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.659" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should be &quot;Auto user Edited&quot; : Actual value is &quot;Auto user&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should be "Auto user Edited" : Actual value is "Auto user"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertEquals(Assertions.java:183)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:508)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.625" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.686" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.982" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.717" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.657" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.786" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.638" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.911" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.686" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.611" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.730" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.666" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.673" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.895" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.648" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.901" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.684" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.692" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.344" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.783" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.544" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.691" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.825" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.678" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.634" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.008" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error type="java.net.URISyntaxException" message="Illegal character in path at index 45: http://10.102.16.61:30001/cms/v1/domainPairs/[]">
      <![CDATA[java.net.URISyntaxException: Illegal character in path at index 45: http://10.102.16.61:30001/cms/v1/domainPairs/[]
	at java.net.URI$Parser.fail(Unknown Source)
	at java.net.URI$Parser.checkChars(Unknown Source)
	at java.net.URI$Parser.parseHierarchical(Unknown Source)
	at java.net.URI$Parser.parse(Unknown Source)
	at java.net.URI.<init>(Unknown Source)
	at io.restassured.internal.http.URIBuilder.convertToURI(URIBuilder.java:91)
	at io.restassured.internal.http.URIBuilder$convertToURI.call(Unknown Source)
	at io.restassured.internal.RequestSpecificationImpl.generateRequestUriForLogging(RequestSpecificationImpl.groovy:1193)
	at sun.reflect.GeneratedMethodAccessor33.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:815)
	at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:174)
	at io.restassured.internal.RequestSpecificationImpl.newFilterContext(RequestSpecificationImpl.groovy:1154)
	at sun.reflect.GeneratedMethodAccessor32.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:815)
	at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
	at io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1729)
	at sun.reflect.GeneratedMethodAccessor65.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:815)
	at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
	at io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1737)
	at sun.reflect.GeneratedMethodAccessor64.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:815)
	at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
	at io.restassured.internal.RequestSpecificationImpl.get(RequestSpecificationImpl.groovy:170)
	at io.restassured.internal.RequestSpecificationImpl.get(RequestSpecificationImpl.groovy)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:210)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </error>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.649" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.703" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.609" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.643" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.791" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.836" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.626" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.009" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error type="java.net.URISyntaxException" message="Illegal character in path at index 45: http://10.102.16.61:30001/cms/v1/domainPairs/[]">
      <![CDATA[java.net.URISyntaxException: Illegal character in path at index 45: http://10.102.16.61:30001/cms/v1/domainPairs/[]
	at java.net.URI$Parser.fail(Unknown Source)
	at java.net.URI$Parser.checkChars(Unknown Source)
	at java.net.URI$Parser.parseHierarchical(Unknown Source)
	at java.net.URI$Parser.parse(Unknown Source)
	at java.net.URI.<init>(Unknown Source)
	at io.restassured.internal.http.URIBuilder.convertToURI(URIBuilder.java:91)
	at io.restassured.internal.http.URIBuilder$convertToURI.call(Unknown Source)
	at io.restassured.internal.RequestSpecificationImpl.generateRequestUriForLogging(RequestSpecificationImpl.groovy:1193)
	at sun.reflect.GeneratedMethodAccessor33.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:815)
	at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:174)
	at io.restassured.internal.RequestSpecificationImpl.newFilterContext(RequestSpecificationImpl.groovy:1154)
	at sun.reflect.GeneratedMethodAccessor32.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:815)
	at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
	at io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1729)
	at sun.reflect.GeneratedMethodAccessor65.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:815)
	at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
	at io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1737)
	at sun.reflect.GeneratedMethodAccessor64.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:815)
	at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
	at io.restassured.internal.RequestSpecificationImpl.put(RequestSpecificationImpl.groovy:178)
	at io.restassured.internal.RequestSpecificationImpl.put(RequestSpecificationImpl.groovy)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:214)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </error>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.845" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.645" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.652" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.739" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.768" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.661" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.835" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.618" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.762" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.642" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.717" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should be &quot;CMName1&quot; : Actual value is &quot;&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should be "CMName1" : Actual value is ""
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertEquals(Assertions.java:183)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:508)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:377)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.662" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.632" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.632" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.630" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.624" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.766" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.626" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.626" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.650" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.786" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.655" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.629" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.626" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.688" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should be &quot;CMName&quot; : Actual value is &quot;&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should be "CMName" : Actual value is ""
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertEquals(Assertions.java:183)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:508)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:377)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.768" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.646" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.795" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should be &quot;RosettaNet&quot; : Actual value is &quot;Gateway&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should be "RosettaNet" : Actual value is "Gateway"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertEquals(Assertions.java:183)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:508)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.623" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.647" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.805" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.625" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.778" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.754" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.930" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.900" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.633" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.709" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should contains &quot;Auto Domain Type  you have entered  is already in use&quot; : Actual value is &quot;Auto Domain Type  you have entered  is already in use&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should contains "Auto Domain Type  you have entered  is already in use" : Actual value is "Auto Domain Type  you have entered  is already in use"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertContains(Assertions.java:212)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:533)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.822" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.637" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.827" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.706" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.770" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.940" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.658" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.633" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.647" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.608" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.647" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.702" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.631" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.805" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.298" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.793" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.813" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.644" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.846" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should contains &quot;The Transport name http_rn  you have entered  is already in use&quot; : Actual value is &quot;The Transport name http_rn  you have entered  is already in use&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should contains "The Transport name http_rn  you have entered  is already in use" : Actual value is "The Transport name http_rn  you have entered  is already in use"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertContains(Assertions.java:212)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:533)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:377)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.645" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should contains &quot;edited&quot; : Actual value is &quot;edited&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should contains "edited" : Actual value is "edited"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertContains(Assertions.java:212)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:533)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:377)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.775" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.637" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.004" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error type="java.net.URISyntaxException" message="Illegal character in path at index 53: http://10.102.16.61:30001/cms/v1/transports/outbound/[]">
      <![CDATA[java.net.URISyntaxException: Illegal character in path at index 53: http://10.102.16.61:30001/cms/v1/transports/outbound/[]
	at java.net.URI$Parser.fail(Unknown Source)
	at java.net.URI$Parser.checkChars(Unknown Source)
	at java.net.URI$Parser.parseHierarchical(Unknown Source)
	at java.net.URI$Parser.parse(Unknown Source)
	at java.net.URI.<init>(Unknown Source)
	at io.restassured.internal.http.URIBuilder.convertToURI(URIBuilder.java:91)
	at io.restassured.internal.http.URIBuilder$convertToURI.call(Unknown Source)
	at io.restassured.internal.RequestSpecificationImpl.generateRequestUriForLogging(RequestSpecificationImpl.groovy:1193)
	at sun.reflect.GeneratedMethodAccessor33.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:815)
	at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:174)
	at io.restassured.internal.RequestSpecificationImpl.newFilterContext(RequestSpecificationImpl.groovy:1154)
	at sun.reflect.GeneratedMethodAccessor32.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:815)
	at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
	at io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1729)
	at sun.reflect.GeneratedMethodAccessor65.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:815)
	at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
	at io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1737)
	at sun.reflect.GeneratedMethodAccessor64.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:815)
	at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
	at io.restassured.internal.RequestSpecificationImpl.get(RequestSpecificationImpl.groovy:170)
	at io.restassured.internal.RequestSpecificationImpl.get(RequestSpecificationImpl.groovy)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:210)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </error>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.717" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.642" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.628" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.631" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should be &quot;CMName&quot; : Actual value is &quot;&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should be "CMName" : Actual value is ""
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertEquals(Assertions.java:183)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:508)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:377)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.621" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.638" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.633" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.672" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.890" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.859" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.620" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.782" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.800" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.822" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.875" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.625" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.619" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.025" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.701" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.621" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.636" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.647" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.824" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.726" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.778" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.742" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.652" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.879" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.734" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.832" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.180" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.649" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.645" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.780" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.931" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.643" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.832" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.723" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.635" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should be &quot;1&quot; : Actual value is &quot;0&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should be "1" : Actual value is "0"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertEquals(Assertions.java:183)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:508)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.648" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.015" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.909" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.944" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.806" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should be &quot;EZComm&quot; : Actual value is &quot;EDIFACT&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should be "EZComm" : Actual value is "EDIFACT"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertEquals(Assertions.java:183)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:508)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.836" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.634" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should be &quot;CMName&quot; : Actual value is &quot;&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should be "CMName" : Actual value is ""
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertEquals(Assertions.java:183)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:508)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:377)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.630" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.858" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.815" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.812" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.716" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.640" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.644" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.618" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.834" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should contains &quot;The Transport name https_rn  you have entered  is already in use&quot; : Actual value is &quot;The Transport name https_rn  you have entered  is already in use&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should contains "The Transport name https_rn  you have entered  is already in use" : Actual value is "The Transport name https_rn  you have entered  is already in use"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertContains(Assertions.java:212)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:533)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:377)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.644" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.663" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should not be &quot;[]&quot; : Actual value is &quot;[]&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should not be "[]" : Actual value is "[]"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertNotEquals(Assertions.java:196)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:520)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.829" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.741" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should be &quot;Auto node0 Edited&quot; : Actual value is &quot;Auto node0&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should be "Auto node0 Edited" : Actual value is "Auto node0"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertEquals(Assertions.java:183)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:508)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:377)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.635" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.865" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.848" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.832" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.627" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should contains &quot;Admin Office  you have entered  is already in use&quot; : Actual value is &quot;Admin Office  you have entered  is already in use&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should contains "Admin Office  you have entered  is already in use" : Actual value is "Admin Office  you have entered  is already in use"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertContains(Assertions.java:212)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:533)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.633" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.624" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.612" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.644" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.678" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.628" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.803" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.662" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.628" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.639" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.860" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.791" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.799" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.661" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.872" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should not be &quot;[]&quot; : Actual value is &quot;[]&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should not be "[]" : Actual value is "[]"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertNotEquals(Assertions.java:196)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:520)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:344)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.793" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.709" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.738" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.633" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should contains &quot;Auto Role Edited  you have entered  is already in use&quot; : Actual value is &quot;Auto Role Edited  you have entered  is already in use&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should contains "Auto Role Edited  you have entered  is already in use" : Actual value is "Auto Role Edited  you have entered  is already in use"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertContains(Assertions.java:212)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:533)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.618" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.638" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.640" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.618" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.627" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.659" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.623" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.794" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.172" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.650" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Unable to store response string to variable or couldn&#039;t received response.">
      <![CDATA[java.lang.AssertionError: Unable to store response string to variable or couldn't received response.
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:415)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.661" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.786" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.845" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.633" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.674" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.639" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.617" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Response Code is 500">
      <![CDATA[java.lang.AssertionError: Response Code is 500
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:460)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.701" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.637" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.615" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.861" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.682" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.700" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.661" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Response Code is 500">
      <![CDATA[java.lang.AssertionError: Response Code is 500
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:460)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.000" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.751" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.750" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.668" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.637" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.733" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.674" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.732" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.744" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.783" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.699" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.621" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should be &quot;CMName1&quot; : Actual value is &quot;&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should be "CMName1" : Actual value is ""
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertEquals(Assertions.java:183)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:508)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:377)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.759" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.630" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.753" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.653" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.795" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.666" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.667" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.667" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.658" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.644" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.618" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should contains &quot;Groupname Auto User group  you have entered  is already in use.&quot; : Actual value is &quot;Groupname Auto User group  you have entered  is already in use.&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should contains "Groupname Auto User group  you have entered  is already in use." : Actual value is "Groupname Auto User group  you have entered  is already in use."
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertContains(Assertions.java:212)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:533)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.624" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.724" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.631" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.671" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.621" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should be &quot;EMAIL&quot; : Actual value is &quot;[&quot;EMAIL&quot;,&quot;FILE&quot;,&quot;FTP&quot;,&quot;HTTP&quot;]&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should be "EMAIL" : Actual value is "["EMAIL","FILE","FTP","HTTP"]"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertEquals(Assertions.java:183)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:508)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:377)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.902" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.647" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.656" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.630" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.665" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should contains &quot;The password you have entered is same as the earlier&quot; : Actual value is &quot;The password you have entered is same as the earlier&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should contains "The password you have entered is same as the earlier" : Actual value is "The password you have entered is same as the earlier"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertContains(Assertions.java:212)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:533)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.617" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.782" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.749" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.832" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.833" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.959" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.646" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.672" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should contains &quot;RosettaNet Role Name  you have entered  is already in use&quot; : Actual value is &quot;RosettaNet Role Name  you have entered  is already in use&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should contains "RosettaNet Role Name  you have entered  is already in use" : Actual value is "RosettaNet Role Name  you have entered  is already in use"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertContains(Assertions.java:212)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:533)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.673" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.660" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.772" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.906" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.639" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Unable to store response string to variable or couldn&#039;t received response.">
      <![CDATA[java.lang.AssertionError: Unable to store response string to variable or couldn't received response.
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:415)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.634" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.818" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.647" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.867" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.956" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.632" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.785" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.629" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.661" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.819" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.647" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.652" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.935" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.697" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.774" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.624" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.775" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.623" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.795" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.632" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.707" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.683" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.761" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.709" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.853" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.637" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.660" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.009" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error type="java.net.URISyntaxException" message="Illegal character in path at index 53: http://10.102.16.61:30001/cms/v1/transports/outbound/[]">
      <![CDATA[java.net.URISyntaxException: Illegal character in path at index 53: http://10.102.16.61:30001/cms/v1/transports/outbound/[]
	at java.net.URI$Parser.fail(Unknown Source)
	at java.net.URI$Parser.checkChars(Unknown Source)
	at java.net.URI$Parser.parseHierarchical(Unknown Source)
	at java.net.URI$Parser.parse(Unknown Source)
	at java.net.URI.<init>(Unknown Source)
	at io.restassured.internal.http.URIBuilder.convertToURI(URIBuilder.java:91)
	at io.restassured.internal.http.URIBuilder$convertToURI.call(Unknown Source)
	at io.restassured.internal.RequestSpecificationImpl.generateRequestUriForLogging(RequestSpecificationImpl.groovy:1193)
	at sun.reflect.GeneratedMethodAccessor33.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:815)
	at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:174)
	at io.restassured.internal.RequestSpecificationImpl.newFilterContext(RequestSpecificationImpl.groovy:1154)
	at sun.reflect.GeneratedMethodAccessor32.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:815)
	at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
	at io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1729)
	at sun.reflect.GeneratedMethodAccessor65.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:815)
	at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
	at io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1737)
	at sun.reflect.GeneratedMethodAccessor64.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:815)
	at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
	at io.restassured.internal.RequestSpecificationImpl.put(RequestSpecificationImpl.groovy:178)
	at io.restassured.internal.RequestSpecificationImpl.put(RequestSpecificationImpl.groovy)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:214)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </error>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.636" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should not be &quot;[]&quot; : Actual value is &quot;[]&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should not be "[]" : Actual value is "[]"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertNotEquals(Assertions.java:196)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:520)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.643" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.625" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.671" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.749" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.646" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should not be &quot;[]&quot; : Actual value is &quot;[]&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should not be "[]" : Actual value is "[]"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertNotEquals(Assertions.java:196)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:520)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.629" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.631" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.648" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.762" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.851" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.701" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.783" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.707" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.785" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.676" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.724" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.669" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
</testsuite> <!-- com.tibco.rest.test.DataDrivenTestCases -->
